version: 0.2
phases:
  install: # Insallation des dépendances
    runtime-versions:
      docker: latest # Version de docker
  pre_build:
    on-failure: ABORT # Si une erreur survient, on arrête le build
    commands:
      - echo "----- Install nodejs, npm & nest.js -----"
      - npm install && npm install -g @nestjs/cli # Installation de nodejs, npm et nest.js
      - echo "Test e2e"
      - npm i --save-dev @nestjs/testing # Installation de nest.js pour les tests
      - npm run test:e2e # Lancement des tests e2e
      - echo "Connexion a AWS ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com # Connexion à AWS ECR
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) # Récupération du hash du commit
      - IMAGE_TAG=${COMMIT_HASH:=latest} # Si le hash du commit n'est pas trouvé, on met latest
  build:
    commands:
      - echo "Build docker image $REPOSITORY_URI:$IMAGE_TAG"
      - docker build -t $REPOSITORY_URI:latest -f Dockerfile . # Construction de l'image docker avec le tag latest
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG  # Construction de l'image docker avec le tag du commit
  post_build:
    commands:
      - echo "Push docker image $REPOSITORY_URI:$IMAGE_TAG"
      - docker push $REPOSITORY_URI:latest # Push de l'image docker avec le tag latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG # Push de l'image docker avec le tag du commit
      - printf '[{"name":"nestjs-graphql","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json # Fichier de définition de l'image docker