version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo -e "----- $APP_NAME -----\n"
      - echo -e "----- Install nodejs, npm & nest.js -----\n"
      - npm install && npm install -g @nestjs/cli
  pre_build:
    commands:
      - echo -e "\nInstall the dependencies needed to run the app INSIDE"
      - npm install
  build:
    commands:
      - echo -e "Build $APP_NAME started on `date`\n"
      - npm run build
artifacts:
  files:
    - '**/*'
  name: $APP_NAME